#############
# Libraries #
#############
import logging

###########
# Modules #
###########
from . models import Users, PropertyStatus, PropertyNames, LocalAuthorityDistricts, Locations, Properties, Base
from . connection import engine, async_session


####################
# Create Structure #
####################
async def create_structure():
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)


###############
# Insert Data #
###############
async def insert_data():
    async with async_session() as session:

        logger = logging.getLogger("lmrun")

        logger.info("Adding dev user")
        user = Users(id=1, username="Developer")
        session.add(user)
        await session.commit()

        logger.info("Adding property status")
        property_status_values = [
            PropertyStatus(id=1, value='Not Visited'),
            PropertyStatus(id=2, value='Visited'),
            PropertyStatus(id=3, value='Owned')
        ]

        session.add_all(property_status_values)
        await session.commit()

        logger.info("Adding property names")
        property_names = [
            PropertyNames(id=1, name="brown1", value=60),
            PropertyNames(id=2, name="brown2", value=60),
            PropertyNames(id=3, name="lightblue1", value=100),
            PropertyNames(id=4, name="lightblue2", value=100),
            PropertyNames(id=5, name="lightblue3", value=120),
            PropertyNames(id=6, name="pink1", value=140),
            PropertyNames(id=7, name="pink2", value=140),
            PropertyNames(id=8, name="pink3", value=160),
            PropertyNames(id=9, name="orange1", value=180),
            PropertyNames(id=10, name="orange2", value=180),
            PropertyNames(id=11, name="orange3", value=200),
            PropertyNames(id=12, name="black1", value=200),
            PropertyNames(id=13, name="black2", value=200),
            PropertyNames(id=14, name="black3", value=200),
            PropertyNames(id=15, name="black4", value=200),
            PropertyNames(id=16, name="red1", value=220),
            PropertyNames(id=17, name="red2", value=220),
            PropertyNames(id=18, name="red3", value=240),
            PropertyNames(id=19, name="yellow1", value=260),
            PropertyNames(id=20, name="yellow2", value=260),
            PropertyNames(id=21, name="yellow3", value=280),
            PropertyNames(id=22, name="green1", value=300),
            PropertyNames(id=23, name="green2", value=300),
            PropertyNames(id=24, name="green3", value=320),
            PropertyNames(id=25, name="darkblue1", value=350),
            PropertyNames(id=26, name="darkblue2", value=400)
        ]

        session.add_all(property_names)
        await session.commit()

        logger.info("Adding local authority districts")
        local_authority_districts = [
            LocalAuthorityDistricts(id=1, local_authority="Hartlepool"),
            LocalAuthorityDistricts(id=2, local_authority="Middlesbrough"),
            LocalAuthorityDistricts(id=3, local_authority="Redcar and Cleveland"),
            LocalAuthorityDistricts(id=4, local_authority="Stockton-on-Tees"),
            LocalAuthorityDistricts(id=5, local_authority="Darlington"),
            LocalAuthorityDistricts(id=6, local_authority="Halton"),
            LocalAuthorityDistricts(id=7, local_authority="Warrington"),
            LocalAuthorityDistricts(id=8, local_authority="Blackburn with Darwen"),
            LocalAuthorityDistricts(id=9, local_authority="Blackpool"),
            LocalAuthorityDistricts(id=10, local_authority="City of Kingston upon Hull"),
            LocalAuthorityDistricts(id=11, local_authority="East Riding of Yorkshire"),
            LocalAuthorityDistricts(id=12, local_authority="North East Lincolnshire"),
            LocalAuthorityDistricts(id=13, local_authority="North Lincolnshire"),
            LocalAuthorityDistricts(id=14, local_authority="York"),
            LocalAuthorityDistricts(id=15, local_authority="Derby"),
            LocalAuthorityDistricts(id=16, local_authority="Leicester"),
            LocalAuthorityDistricts(id=17, local_authority="Rutland"),
            LocalAuthorityDistricts(id=18, local_authority="Nottingham"),
            LocalAuthorityDistricts(id=19, local_authority="County of Herefordshire"),
            LocalAuthorityDistricts(id=20, local_authority="Telford and Wrekin"),
            LocalAuthorityDistricts(id=21, local_authority="Stoke-on-Trent"),
            LocalAuthorityDistricts(id=22, local_authority="Bath and North East Somerset"),
            LocalAuthorityDistricts(id=23, local_authority="City of Bristol "),
            LocalAuthorityDistricts(id=24, local_authority="North Somerset"),
            LocalAuthorityDistricts(id=25, local_authority="South Gloucestershire"),
            LocalAuthorityDistricts(id=26, local_authority="Plymouth"),
            LocalAuthorityDistricts(id=27, local_authority="Torbay"),
            LocalAuthorityDistricts(id=28, local_authority="Swindon"),
            LocalAuthorityDistricts(id=29, local_authority="Peterborough"),
            LocalAuthorityDistricts(id=30, local_authority="Luton"),
            LocalAuthorityDistricts(id=31, local_authority="Southend-on-Sea"),
            LocalAuthorityDistricts(id=32, local_authority="Thurrock"),
            LocalAuthorityDistricts(id=33, local_authority="Medway"),
            LocalAuthorityDistricts(id=34, local_authority="Bracknell Forest"),
            LocalAuthorityDistricts(id=35, local_authority="West Berkshire"),
            LocalAuthorityDistricts(id=36, local_authority="Reading"),
            LocalAuthorityDistricts(id=37, local_authority="Slough"),
            LocalAuthorityDistricts(id=38, local_authority="Windsor and Maidenhead"),
            LocalAuthorityDistricts(id=39, local_authority="Wokingham"),
            LocalAuthorityDistricts(id=40, local_authority="Milton Keynes"),
            LocalAuthorityDistricts(id=41, local_authority="Brighton and Hove"),
            LocalAuthorityDistricts(id=42, local_authority="Portsmouth"),
            LocalAuthorityDistricts(id=43, local_authority="Southampton"),
            LocalAuthorityDistricts(id=44, local_authority="Isle of Wight"),
            LocalAuthorityDistricts(id=45, local_authority="County Durham"),
            LocalAuthorityDistricts(id=46, local_authority="Cheshire East"),
            LocalAuthorityDistricts(id=47, local_authority="Cheshire West and Chester"),
            LocalAuthorityDistricts(id=48, local_authority="Shropshire"),
            LocalAuthorityDistricts(id=49, local_authority="Cornwall"),
            LocalAuthorityDistricts(id=50, local_authority="Isles of Scilly"),
            LocalAuthorityDistricts(id=51, local_authority="Wiltshire"),
            LocalAuthorityDistricts(id=52, local_authority="Bedford"),
            LocalAuthorityDistricts(id=53, local_authority="Central Bedfordshire"),
            LocalAuthorityDistricts(id=54, local_authority="Northumberland"),
            LocalAuthorityDistricts(id=55, local_authority="Bournemouth, Christchurch and Poole"),
            LocalAuthorityDistricts(id=56, local_authority="Dorset"),
            LocalAuthorityDistricts(id=57, local_authority="Buckinghamshire"),
            LocalAuthorityDistricts(id=58, local_authority="North Northamptonshire"),
            LocalAuthorityDistricts(id=59, local_authority="West Northamptonshire"),
            LocalAuthorityDistricts(id=60, local_authority="Cambridge"),
            LocalAuthorityDistricts(id=61, local_authority="East Cambridgeshire"),
            LocalAuthorityDistricts(id=62, local_authority="Fenland"),
            LocalAuthorityDistricts(id=63, local_authority="Huntingdonshire"),
            LocalAuthorityDistricts(id=64, local_authority="South Cambridgeshire"),
            LocalAuthorityDistricts(id=65, local_authority="Allerdale"),
            LocalAuthorityDistricts(id=66, local_authority="Barrow-in-Furness"),
            LocalAuthorityDistricts(id=67, local_authority="Carlisle"),
            LocalAuthorityDistricts(id=68, local_authority="Copeland"),
            LocalAuthorityDistricts(id=69, local_authority="Eden"),
            LocalAuthorityDistricts(id=70, local_authority="South Lakeland"),
            LocalAuthorityDistricts(id=71, local_authority="Amber Valley"),
            LocalAuthorityDistricts(id=72, local_authority="Bolsover"),
            LocalAuthorityDistricts(id=73, local_authority="Chesterfield"),
            LocalAuthorityDistricts(id=74, local_authority="Derbyshire Dales"),
            LocalAuthorityDistricts(id=75, local_authority="Erewash"),
            LocalAuthorityDistricts(id=76, local_authority="High Peak"),
            LocalAuthorityDistricts(id=77, local_authority="North East Derbyshire"),
            LocalAuthorityDistricts(id=78, local_authority="South Derbyshire"),
            LocalAuthorityDistricts(id=79, local_authority="East Devon"),
            LocalAuthorityDistricts(id=80, local_authority="Exeter"),
            LocalAuthorityDistricts(id=81, local_authority="Mid Devon"),
            LocalAuthorityDistricts(id=82, local_authority="North Devon"),
            LocalAuthorityDistricts(id=83, local_authority="South Hams"),
            LocalAuthorityDistricts(id=84, local_authority="Teignbridge"),
            LocalAuthorityDistricts(id=85, local_authority="Torridge"),
            LocalAuthorityDistricts(id=86, local_authority="West Devon"),
            LocalAuthorityDistricts(id=87, local_authority="Eastbourne"),
            LocalAuthorityDistricts(id=88, local_authority="Hastings"),
            LocalAuthorityDistricts(id=89, local_authority="Lewes"),
            LocalAuthorityDistricts(id=90, local_authority="Rother"),
            LocalAuthorityDistricts(id=91, local_authority="Wealden"),
            LocalAuthorityDistricts(id=92, local_authority="Basildon"),
            LocalAuthorityDistricts(id=93, local_authority="Braintree"),
            LocalAuthorityDistricts(id=94, local_authority="Brentwood"),
            LocalAuthorityDistricts(id=95, local_authority="Castle Point"),
            LocalAuthorityDistricts(id=96, local_authority="Chelmsford"),
            LocalAuthorityDistricts(id=97, local_authority="Colchester"),
            LocalAuthorityDistricts(id=98, local_authority="Epping Forest"),
            LocalAuthorityDistricts(id=99, local_authority="Harlow"),
            LocalAuthorityDistricts(id=100, local_authority="Maldon"),
            LocalAuthorityDistricts(id=101, local_authority="Rochford"),
            LocalAuthorityDistricts(id=102, local_authority="Tendring"),
            LocalAuthorityDistricts(id=103, local_authority="Uttlesford"),
            LocalAuthorityDistricts(id=104, local_authority="Cheltenham"),
            LocalAuthorityDistricts(id=105, local_authority="Cotswold"),
            LocalAuthorityDistricts(id=106, local_authority="Forest of Dean"),
            LocalAuthorityDistricts(id=107, local_authority="Gloucester"),
            LocalAuthorityDistricts(id=108, local_authority="Stroud"),
            LocalAuthorityDistricts(id=109, local_authority="Tewkesbury"),
            LocalAuthorityDistricts(id=110, local_authority="Basingstoke and Deane"),
            LocalAuthorityDistricts(id=111, local_authority="East Hampshire"),
            LocalAuthorityDistricts(id=112, local_authority="Eastleigh"),
            LocalAuthorityDistricts(id=113, local_authority="Fareham"),
            LocalAuthorityDistricts(id=114, local_authority="Gosport"),
            LocalAuthorityDistricts(id=115, local_authority="Hart"),
            LocalAuthorityDistricts(id=116, local_authority="Havant"),
            LocalAuthorityDistricts(id=117, local_authority="New Forest"),
            LocalAuthorityDistricts(id=118, local_authority="Rushmoor"),
            LocalAuthorityDistricts(id=119, local_authority="Test Valley"),
            LocalAuthorityDistricts(id=120, local_authority="Winchester"),
            LocalAuthorityDistricts(id=121, local_authority="Broxbourne"),
            LocalAuthorityDistricts(id=122, local_authority="Dacorum"),
            LocalAuthorityDistricts(id=123, local_authority="Hertsmere"),
            LocalAuthorityDistricts(id=124, local_authority="North Hertfordshire"),
            LocalAuthorityDistricts(id=125, local_authority="Three Rivers"),
            LocalAuthorityDistricts(id=126, local_authority="Watford"),
            LocalAuthorityDistricts(id=127, local_authority="Ashford"),
            LocalAuthorityDistricts(id=128, local_authority="Canterbury"),
            LocalAuthorityDistricts(id=129, local_authority="Dartford"),
            LocalAuthorityDistricts(id=130, local_authority="Dover"),
            LocalAuthorityDistricts(id=131, local_authority="Gravesham"),
            LocalAuthorityDistricts(id=132, local_authority="Maidstone"),
            LocalAuthorityDistricts(id=133, local_authority="Sevenoaks"),
            LocalAuthorityDistricts(id=134, local_authority="Folkestone and Hythe"),
            LocalAuthorityDistricts(id=135, local_authority="Swale"),
            LocalAuthorityDistricts(id=136, local_authority="Thanet"),
            LocalAuthorityDistricts(id=137, local_authority="Tonbridge and Malling"),
            LocalAuthorityDistricts(id=138, local_authority="Tunbridge Wells"),
            LocalAuthorityDistricts(id=139, local_authority="Burnley"),
            LocalAuthorityDistricts(id=140, local_authority="Chorley"),
            LocalAuthorityDistricts(id=141, local_authority="Fylde"),
            LocalAuthorityDistricts(id=142, local_authority="Hyndburn"),
            LocalAuthorityDistricts(id=143, local_authority="Lancaster"),
            LocalAuthorityDistricts(id=144, local_authority="Pendle"),
            LocalAuthorityDistricts(id=145, local_authority="Preston"),
            LocalAuthorityDistricts(id=146, local_authority="Ribble Valley"),
            LocalAuthorityDistricts(id=147, local_authority="Rossendale"),
            LocalAuthorityDistricts(id=148, local_authority="South Ribble"),
            LocalAuthorityDistricts(id=149, local_authority="West Lancashire"),
            LocalAuthorityDistricts(id=150, local_authority="Wyre"),
            LocalAuthorityDistricts(id=151, local_authority="Blaby"),
            LocalAuthorityDistricts(id=152, local_authority="Charnwood"),
            LocalAuthorityDistricts(id=153, local_authority="Harborough"),
            LocalAuthorityDistricts(id=154, local_authority="Hinckley and Bosworth"),
            LocalAuthorityDistricts(id=155, local_authority="Melton"),
            LocalAuthorityDistricts(id=156, local_authority="North West Leicestershire"),
            LocalAuthorityDistricts(id=157, local_authority="Oadby and Wigston"),
            LocalAuthorityDistricts(id=158, local_authority="Boston"),
            LocalAuthorityDistricts(id=159, local_authority="East Lindsey"),
            LocalAuthorityDistricts(id=160, local_authority="Lincoln"),
            LocalAuthorityDistricts(id=161, local_authority="North Kesteven"),
            LocalAuthorityDistricts(id=162, local_authority="South Holland"),
            LocalAuthorityDistricts(id=163, local_authority="South Kesteven"),
            LocalAuthorityDistricts(id=164, local_authority="West Lindsey"),
            LocalAuthorityDistricts(id=165, local_authority="Breckland"),
            LocalAuthorityDistricts(id=166, local_authority="Broadland"),
            LocalAuthorityDistricts(id=167, local_authority="Great Yarmouth"),
            LocalAuthorityDistricts(id=168, local_authority="King's Lynn and West Norfolk"),
            LocalAuthorityDistricts(id=169, local_authority="North Norfolk"),
            LocalAuthorityDistricts(id=170, local_authority="Norwich"),
            LocalAuthorityDistricts(id=171, local_authority="South Norfolk"),
            LocalAuthorityDistricts(id=172, local_authority="Craven"),
            LocalAuthorityDistricts(id=173, local_authority="Hambleton"),
            LocalAuthorityDistricts(id=174, local_authority="Harrogate"),
            LocalAuthorityDistricts(id=175, local_authority="Richmondshire"),
            LocalAuthorityDistricts(id=176, local_authority="Ryedale"),
            LocalAuthorityDistricts(id=177, local_authority="Scarborough"),
            LocalAuthorityDistricts(id=178, local_authority="Selby"),
            LocalAuthorityDistricts(id=179, local_authority="Ashfield"),
            LocalAuthorityDistricts(id=180, local_authority="Bassetlaw"),
            LocalAuthorityDistricts(id=181, local_authority="Broxtowe"),
            LocalAuthorityDistricts(id=182, local_authority="Gedling"),
            LocalAuthorityDistricts(id=183, local_authority="Mansfield"),
            LocalAuthorityDistricts(id=184, local_authority="Newark and Sherwood"),
            LocalAuthorityDistricts(id=185, local_authority="Rushcliffe"),
            LocalAuthorityDistricts(id=186, local_authority="Cherwell"),
            LocalAuthorityDistricts(id=187, local_authority="Oxford"),
            LocalAuthorityDistricts(id=188, local_authority="South Oxfordshire"),
            LocalAuthorityDistricts(id=189, local_authority="Vale of White Horse"),
            LocalAuthorityDistricts(id=190, local_authority="West Oxfordshire"),
            LocalAuthorityDistricts(id=191, local_authority="Mendip"),
            LocalAuthorityDistricts(id=192, local_authority="Sedgemoor"),
            LocalAuthorityDistricts(id=193, local_authority="South Somerset"),
            LocalAuthorityDistricts(id=194, local_authority="Cannock Chase"),
            LocalAuthorityDistricts(id=195, local_authority="East Staffordshire"),
            LocalAuthorityDistricts(id=196, local_authority="Lichfield"),
            LocalAuthorityDistricts(id=197, local_authority="Newcastle-under-Lyme"),
            LocalAuthorityDistricts(id=198, local_authority="South Staffordshire"),
            LocalAuthorityDistricts(id=199, local_authority="Stafford"),
            LocalAuthorityDistricts(id=200, local_authority="Staffordshire Moorlands"),
            LocalAuthorityDistricts(id=201, local_authority="Tamworth"),
            LocalAuthorityDistricts(id=202, local_authority="Babergh"),
            LocalAuthorityDistricts(id=203, local_authority="Ipswich"),
            LocalAuthorityDistricts(id=204, local_authority="Mid Suffolk"),
            LocalAuthorityDistricts(id=205, local_authority="Elmbridge"),
            LocalAuthorityDistricts(id=206, local_authority="Epsom and Ewell"),
            LocalAuthorityDistricts(id=207, local_authority="Guildford"),
            LocalAuthorityDistricts(id=208, local_authority="Mole Valley"),
            LocalAuthorityDistricts(id=209, local_authority="Reigate and Banstead"),
            LocalAuthorityDistricts(id=210, local_authority="Runnymede"),
            LocalAuthorityDistricts(id=211, local_authority="Spelthorne"),
            LocalAuthorityDistricts(id=212, local_authority="Surrey Heath"),
            LocalAuthorityDistricts(id=213, local_authority="Tandridge"),
            LocalAuthorityDistricts(id=214, local_authority="Waverley"),
            LocalAuthorityDistricts(id=215, local_authority="Woking"),
            LocalAuthorityDistricts(id=216, local_authority="North Warwickshire"),
            LocalAuthorityDistricts(id=217, local_authority="Nuneaton and Bedworth"),
            LocalAuthorityDistricts(id=218, local_authority="Rugby"),
            LocalAuthorityDistricts(id=219, local_authority="Stratford-on-Avon"),
            LocalAuthorityDistricts(id=220, local_authority="Warwick"),
            LocalAuthorityDistricts(id=221, local_authority="Adur"),
            LocalAuthorityDistricts(id=222, local_authority="Arun"),
            LocalAuthorityDistricts(id=223, local_authority="Chichester"),
            LocalAuthorityDistricts(id=224, local_authority="Crawley"),
            LocalAuthorityDistricts(id=225, local_authority="Horsham"),
            LocalAuthorityDistricts(id=226, local_authority="Mid Sussex"),
            LocalAuthorityDistricts(id=227, local_authority="Worthing"),
            LocalAuthorityDistricts(id=228, local_authority="Bromsgrove"),
            LocalAuthorityDistricts(id=229, local_authority="Malvern Hills"),
            LocalAuthorityDistricts(id=230, local_authority="Redditch"),
            LocalAuthorityDistricts(id=231, local_authority="Worcester"),
            LocalAuthorityDistricts(id=232, local_authority="Wychavon"),
            LocalAuthorityDistricts(id=233, local_authority="Wyre Forest"),
            LocalAuthorityDistricts(id=234, local_authority="St Albans"),
            LocalAuthorityDistricts(id=235, local_authority="Welwyn Hatfield"),
            LocalAuthorityDistricts(id=236, local_authority="East Hertfordshire"),
            LocalAuthorityDistricts(id=237, local_authority="Stevenage"),
            LocalAuthorityDistricts(id=238, local_authority="East Suffolk"),
            LocalAuthorityDistricts(id=239, local_authority="West Suffolk"),
            LocalAuthorityDistricts(id=240, local_authority="Somerset West and Taunton"),
            LocalAuthorityDistricts(id=241, local_authority="Bolton"),
            LocalAuthorityDistricts(id=242, local_authority="Bury"),
            LocalAuthorityDistricts(id=243, local_authority="Manchester"),
            LocalAuthorityDistricts(id=244, local_authority="Oldham"),
            LocalAuthorityDistricts(id=245, local_authority="Rochdale"),
            LocalAuthorityDistricts(id=246, local_authority="Salford"),
            LocalAuthorityDistricts(id=247, local_authority="Stockport"),
            LocalAuthorityDistricts(id=248, local_authority="Tameside"),
            LocalAuthorityDistricts(id=249, local_authority="Trafford"),
            LocalAuthorityDistricts(id=250, local_authority="Wigan"),
            LocalAuthorityDistricts(id=251, local_authority="Knowsley"),
            LocalAuthorityDistricts(id=252, local_authority="Liverpool"),
            LocalAuthorityDistricts(id=253, local_authority="St. Helens"),
            LocalAuthorityDistricts(id=254, local_authority="Sefton"),
            LocalAuthorityDistricts(id=255, local_authority="Wirral"),
            LocalAuthorityDistricts(id=256, local_authority="Barnsley"),
            LocalAuthorityDistricts(id=257, local_authority="Doncaster"),
            LocalAuthorityDistricts(id=258, local_authority="Rotherham"),
            LocalAuthorityDistricts(id=259, local_authority="Sheffield"),
            LocalAuthorityDistricts(id=260, local_authority="Newcastle upon Tyne"),
            LocalAuthorityDistricts(id=261, local_authority="North Tyneside"),
            LocalAuthorityDistricts(id=262, local_authority="South Tyneside"),
            LocalAuthorityDistricts(id=263, local_authority="Sunderland"),
            LocalAuthorityDistricts(id=264, local_authority="Birmingham"),
            LocalAuthorityDistricts(id=265, local_authority="Coventry"),
            LocalAuthorityDistricts(id=266, local_authority="Dudley"),
            LocalAuthorityDistricts(id=267, local_authority="Sandwell"),
            LocalAuthorityDistricts(id=268, local_authority="Solihull"),
            LocalAuthorityDistricts(id=269, local_authority="Walsall"),
            LocalAuthorityDistricts(id=270, local_authority="Wolverhampton"),
            LocalAuthorityDistricts(id=271, local_authority="Bradford"),
            LocalAuthorityDistricts(id=272, local_authority="Calderdale"),
            LocalAuthorityDistricts(id=273, local_authority="Kirklees"),
            LocalAuthorityDistricts(id=274, local_authority="Leeds"),
            LocalAuthorityDistricts(id=275, local_authority="Wakefield"),
            LocalAuthorityDistricts(id=276, local_authority="Gateshead"),
            LocalAuthorityDistricts(id=277, local_authority="City of London"),
            LocalAuthorityDistricts(id=278, local_authority="Barking and Dagenham"),
            LocalAuthorityDistricts(id=279, local_authority="Barnet"),
            LocalAuthorityDistricts(id=280, local_authority="Bexley"),
            LocalAuthorityDistricts(id=281, local_authority="Brent"),
            LocalAuthorityDistricts(id=282, local_authority="Bromley"),
            LocalAuthorityDistricts(id=283, local_authority="Camden"),
            LocalAuthorityDistricts(id=284, local_authority="Croydon"),
            LocalAuthorityDistricts(id=285, local_authority="Ealing"),
            LocalAuthorityDistricts(id=286, local_authority="Enfield"),
            LocalAuthorityDistricts(id=287, local_authority="Greenwich"),
            LocalAuthorityDistricts(id=288, local_authority="Hackney"),
            LocalAuthorityDistricts(id=289, local_authority="Hammersmith and Fulham"),
            LocalAuthorityDistricts(id=290, local_authority="Haringey"),
            LocalAuthorityDistricts(id=291, local_authority="Harrow"),
            LocalAuthorityDistricts(id=292, local_authority="Havering"),
            LocalAuthorityDistricts(id=293, local_authority="Hillingdon"),
            LocalAuthorityDistricts(id=294, local_authority="Hounslow"),
            LocalAuthorityDistricts(id=295, local_authority="Islington"),
            LocalAuthorityDistricts(id=296, local_authority="Kensington and Chelsea"),
            LocalAuthorityDistricts(id=297, local_authority="Kingston upon Thames"),
            LocalAuthorityDistricts(id=298, local_authority="Lambeth"),
            LocalAuthorityDistricts(id=299, local_authority="Lewisham"),
            LocalAuthorityDistricts(id=300, local_authority="Merton"),
            LocalAuthorityDistricts(id=301, local_authority="Newham"),
            LocalAuthorityDistricts(id=302, local_authority="Redbridge"),
            LocalAuthorityDistricts(id=303, local_authority="Richmond upon Thames"),
            LocalAuthorityDistricts(id=304, local_authority="Southwark"),
            LocalAuthorityDistricts(id=305, local_authority="Sutton"),
            LocalAuthorityDistricts(id=306, local_authority="Tower Hamlets"),
            LocalAuthorityDistricts(id=307, local_authority="Waltham Forest"),
            LocalAuthorityDistricts(id=308, local_authority="Wandsworth"),
            LocalAuthorityDistricts(id=309, local_authority="Westminster"),
            LocalAuthorityDistricts(id=310, local_authority="Antrim and Newtownabbey"),
            LocalAuthorityDistricts(id=311, local_authority="Armagh City, Banbridge and Craigavon"),
            LocalAuthorityDistricts(id=312, local_authority="Belfast"),
            LocalAuthorityDistricts(id=313, local_authority="Causeway Coast and Glens"),
            LocalAuthorityDistricts(id=314, local_authority="Derry City and Strabane"),
            LocalAuthorityDistricts(id=315, local_authority="Fermanagh and Omagh"),
            LocalAuthorityDistricts(id=316, local_authority="Lisburn and Castlereagh"),
            LocalAuthorityDistricts(id=317, local_authority="Mid and East Antrim"),
            LocalAuthorityDistricts(id=318, local_authority="Mid Ulster"),
            LocalAuthorityDistricts(id=319, local_authority="Newry, Mourne and Down"),
            LocalAuthorityDistricts(id=320, local_authority="Ards and North Down"),
            LocalAuthorityDistricts(id=321, local_authority="Clackmannanshire"),
            LocalAuthorityDistricts(id=322, local_authority="Dumfries and Galloway"),
            LocalAuthorityDistricts(id=323, local_authority="East Ayrshire"),
            LocalAuthorityDistricts(id=324, local_authority="East Lothian"),
            LocalAuthorityDistricts(id=325, local_authority="East Renfrewshire"),
            LocalAuthorityDistricts(id=326, local_authority="Na h-Eileanan Siar"),
            LocalAuthorityDistricts(id=327, local_authority="Falkirk"),
            LocalAuthorityDistricts(id=328, local_authority="Highland"),
            LocalAuthorityDistricts(id=329, local_authority="Inverclyde"),
            LocalAuthorityDistricts(id=330, local_authority="Midlothian"),
            LocalAuthorityDistricts(id=331, local_authority="Moray"),
            LocalAuthorityDistricts(id=332, local_authority="North Ayrshire"),
            LocalAuthorityDistricts(id=333, local_authority="Orkney Islands"),
            LocalAuthorityDistricts(id=334, local_authority="Scottish Borders"),
            LocalAuthorityDistricts(id=335, local_authority="Shetland Islands"),
            LocalAuthorityDistricts(id=336, local_authority="South Ayrshire"),
            LocalAuthorityDistricts(id=337, local_authority="South Lanarkshire"),
            LocalAuthorityDistricts(id=338, local_authority="Stirling"),
            LocalAuthorityDistricts(id=339, local_authority="Aberdeen City"),
            LocalAuthorityDistricts(id=340, local_authority="Aberdeenshire"),
            LocalAuthorityDistricts(id=341, local_authority="Argyll and Bute"),
            LocalAuthorityDistricts(id=342, local_authority="City of Edinburgh"),
            LocalAuthorityDistricts(id=343, local_authority="Renfrewshire"),
            LocalAuthorityDistricts(id=344, local_authority="West Dunbartonshire"),
            LocalAuthorityDistricts(id=345, local_authority="West Lothian"),
            LocalAuthorityDistricts(id=346, local_authority="Angus"),
            LocalAuthorityDistricts(id=347, local_authority="Dundee City"),
            LocalAuthorityDistricts(id=348, local_authority="East Dunbartonshire"),
            LocalAuthorityDistricts(id=349, local_authority="Fife"),
            LocalAuthorityDistricts(id=350, local_authority="Perth and Kinross"),
            LocalAuthorityDistricts(id=351, local_authority="Glasgow City"),
            LocalAuthorityDistricts(id=352, local_authority="North Lanarkshire"),
            LocalAuthorityDistricts(id=353, local_authority="Isle of Anglesey"),
            LocalAuthorityDistricts(id=354, local_authority="Gwynedd"),
            LocalAuthorityDistricts(id=355, local_authority="Conwy"),
            LocalAuthorityDistricts(id=356, local_authority="Denbighshire"),
            LocalAuthorityDistricts(id=357, local_authority="Flintshire"),
            LocalAuthorityDistricts(id=358, local_authority="Wrexham"),
            LocalAuthorityDistricts(id=359, local_authority="Ceredigion"),
            LocalAuthorityDistricts(id=360, local_authority="Pembrokeshire"),
            LocalAuthorityDistricts(id=361, local_authority="Carmarthenshire"),
            LocalAuthorityDistricts(id=362, local_authority="Swansea"),
            LocalAuthorityDistricts(id=363, local_authority="Neath Port Talbot"),
            LocalAuthorityDistricts(id=364, local_authority="Bridgend"),
            LocalAuthorityDistricts(id=365, local_authority="Vale of Glamorgan"),
            LocalAuthorityDistricts(id=366, local_authority="Cardiff"),
            LocalAuthorityDistricts(id=367, local_authority="Rhondda Cynon Taf"),
            LocalAuthorityDistricts(id=368, local_authority="Caerphilly"),
            LocalAuthorityDistricts(id=369, local_authority="Blaenau Gwent"),
            LocalAuthorityDistricts(id=370, local_authority="Torfaen"),
            LocalAuthorityDistricts(id=371, local_authority="Monmouthshire"),
            LocalAuthorityDistricts(id=372, local_authority="Newport"),
            LocalAuthorityDistricts(id=373, local_authority="Powys"),
            LocalAuthorityDistricts(id=374, local_authority="Merthyr Tydfil")
        ]

        session.add_all(local_authority_districts)
        await session.commit()

        logger.info("Adding demo location")
        location = Locations(name="London", author_id=1, local_authority_id=277, difficulty=1, description="Initial location based around the original London Monopoly Properties")
        session.add(location)
        await session.commit()

        logger.info("Adding properties for demo location")
        properties = [
            Properties(
                location_id=location.id,
                property_id=1,
                name="Old Kent Road",
                question="Which well known supermarket backs onto the corner of old kent roadand Ossory Rd",
                answer="Asda"
            ),
            Properties(
                location_id=location.id,
                property_id=2,
                name="Whitechapel Road",
                question="In which year was AMBLA (the finest Asian Confectionary) established",
                answer="1965"
            ),
            Properties(
                location_id=location.id,
                property_id=3,
                name="Angel Islington",
                question="What colour scooter is parked outside The Angel, Weatherspoon Pub",
                answer="Red"
            ),
            Properties(
                location_id=location.id,
                property_id=4,
                name="Euston Road",
                question="According to he posters at Friends House, what should one do in turbulent times.",
                answer="Be a Quaker"
            ),
            Properties(
                location_id=location.id,
                property_id=5,
                name="Pentonville Road",
                question="What kind of people / special need should motorists be wary of, at the crossing on Pentonville Rd",
                answer="Deaf, Blind people"
            ),
            Properties(
                location_id=location.id,
                property_id=6,
                name="Pall Mall",
                question="How many soldiers are there on the Crimean War Memorial",
                answer="Three (3)"
            ),
            Properties(
                location_id=location.id,
                property_id=7,
                name="Whitehall ",
                question="What number bus is going past Downing Street ",
                answer="87"
            ),
            Properties(
                location_id=location.id,
                property_id=8,
                name="Northumberland Ave",
                question="Who laid the stone at Citadines",
                answer="Edward Prince of Wales"
            ),
            Properties(
                location_id=location.id,
                property_id=9,
                name="Bow Street",
                question="How many columns does the building flying 2 red flags have",
                answer="Six (6)"
            ),
            Properties(
                location_id=location.id,
                property_id=10,
                name="Marlborough Street",
                question="Who sold out at the London Palladium",
                answer="Jimmy Buffet"
            ),
            Properties(
                location_id=location.id,
                property_id=11,
                name="Vine Street",
                question="Which company is on the 3rd floor  of One Vine Street",
                answer="No One - It's Vacant"
            ),
            Properties(
                location_id=location.id,
                property_id=12,
                name="London Kings Cross",
                question="When looking at the entrance from the road, what kind of emergency vehicles are parked outside and how many are there",
                answer="Police Vans (3)"
            ),
            Properties(
                location_id=location.id,
                property_id=13,
                name="Fenchurch Street Station",
                question="How many sets of blue doors are there at the main entrance",
                answer="7"
            ),
            Properties(
                location_id=location.id,
                property_id=14,
                name="Liverpool Street",
                question="What is the name of the construction company working on the crossrail project outside the main entrance",
                answer="Taylor Woodrow / Laing O'Rourke"
            ),
            Properties(
                location_id=location.id,
                property_id=15,
                name="Marylebone Station",
                question="What do the two red signs outside the station say",
                answer="You have to wear a face covering, unless exempt"
            ),
            Properties(
                location_id=location.id,
                property_id=16,
                name="The Strand",
                question="What is showing at the Savoy Theatre",
                answer="9 to 5"
            ),
            Properties(
                location_id=location.id,
                property_id=17,
                name="Fleet Street",
                question="What time is it at the Romanian St George church",
                answer="12:50, Ten to One"
            ),
            Properties(
                location_id=location.id,
                property_id=18,
                name="Trafalgar Square",
                question="When was Charles James Napier Born",
                answer="MDCCLXXXII"
            ),
            Properties(
                location_id=location.id,
                property_id=19,
                name="Leicester Square",
                question="How old will the grounds of this decorated square be on 2nd July 2021",
                answer="147 years"
            ),
            Properties(
                location_id=location.id,
                property_id=20,
                name="Coventry Street",
                question="In which year was The \"Original Tour\" on this street established",
                answer="1951"
            ),
            Properties(
                location_id=location.id,
                property_id=21,
                name="Picadilly",
                question="On the steps of a famous, loving monument a pair of seemingly identical twins are sitting down for a romantic spot of lunch.  But where did they buy it from",
                answer="Tesco"
            ),
            Properties(
                location_id=location.id,
                property_id=22,
                name="Regent Street",
                question="On which floors of the famous London toy store are the Noble Collecton",
                answer="Fourth and Lower Ground Floors"
            ),
            Properties(
                location_id=location.id,
                property_id=23,
                name="Oxford Street",
                question="What is written in the window of the shop is across the road from Oxford Circus on Oxford Street",
                answer="Top Shop-\"The Ones We Love\""
            ),
            Properties(
                location_id=location.id,
                property_id=24,
                name="New Bond Street",
                question="Who made the horse and rider where New meets Old.",
                answer="Elizabeth Frink"
            ),
            Properties(
                location_id=location.id,
                property_id=25,
                name="Park Lane",
                question="What is the four letter code for the Congestion Charge Zone starting in this area.  And how far is it.",
                answer="ULEZ (25yds)"
            ),
            Properties(
                location_id=location.id,
                property_id=26,
                name="Mayfair",
                question="What Boats Can You Buy near here, and what is the phone number for the shop.",
                answer="Sunseeker, 0207 4933441, 07774 720652 (Davies St / Grosvenor St)"
            )
        ]

        session.add_all(properties)
        await session.commit()
